spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:80/mgtv?useUnicode=true&characterEncoding=utf-8
    username: shang
    password: shang
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      #     更新或者创建数据表结构
      ddl-auto: update
    #    控制台显示SQL
    show-sql: true



